#! /bin/sh
#  @(#) create_dmiess  McKie  Nov-1999
#  This Bourne script creates the dmiess.f source file
#  from the dmiess.f.template file.
#
#  Expecting 2 arguments:
#
#   Arg 1:  Path to rm command
#
#   Arg 2:  Name of generic intrinsic function to take imaginary part
#           of complex number
#
#
#  Define name of this script
#
THIS_SCRIPT="create_dmiess"
#
#
#  Check for unexpected number of command line arguments
#
if [ $# -ne 2 ] ; then
 echo "${THIS_SCRIPT}:  Error--Unexpected # command line args" 
 exit 1
fi
#
#
#  Assign command line args to convenient symbols
#
RM="$1"
IMAG="$2"
#
#
#  Report what will happen
#
echo "${THIS_SCRIPT}: Creating dmiess.f from dmiess.f.template"
echo "${THIS_SCRIPT}: Using $IMAG as generic intrinsic imag() function"
#
#
#  If alternative generic intrinsic is "imag" then use template file as is
#
if [ \( "$IMAG" = "imag" \) -o \( "$IMAG" = "IMAG" \) ] ; then
 echo "${THIS_SCRIPT}:" "cp dmiess.f.template dmiess.f"
 cp dmiess.f.template dmiess.f
#
#
#  If alternative generic intrinsic is not "imag", activate stmt function
#  in template file to use alternative function in place of imag()
#
else
 E1="/^c--alt_imag/s/alt_function/$IMAG/"
 E2="/^c--alt_imag/s/c--alt_imag//"
 echo "${THIS_SCRIPT}:"  $RM dmiess.f
 $RM dmiess.f
 echo "${THIS_SCRIPT}:"  sed -e "$E1" -e "$E2" dmiess.f.template 
 sed -e "$E1" -e "$E2" dmiess.f.template  > dmiess.f
fi
#
#
#  Terminate normally
#
exit 0
